# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/Master_constraints/PYNQ-Z1_C.xdc

# Block Designs: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/rsa_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc || ORIG_REF_NAME==rsa_soc} -quiet] -quiet

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rsa_dma_0/rsa_soc_rsa_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_dma_0 || ORIG_REF_NAME==rsa_soc_rsa_dma_0} -quiet] -quiet

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rsa_acc_0/rsa_soc_rsa_acc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_acc_0 || ORIG_REF_NAME==rsa_soc_rsa_acc_0} -quiet] -quiet

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/rsa_soc_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_axi_smc_0 || ORIG_REF_NAME==rsa_soc_axi_smc_0} -quiet] -quiet

# Block Designs: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/bd_ae75.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_0/bd_ae75_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_1/bd_ae75_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_2/bd_ae75_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_3/bd_ae75_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_4/bd_ae75_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_5/bd_ae75_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_6/bd_ae75_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_7/bd_ae75_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_8/bd_ae75_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_9/bd_ae75_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_10/bd_ae75_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_11/bd_ae75_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_12/bd_ae75_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_13/bd_ae75_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_14/bd_ae75_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_15/bd_ae75_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_16/bd_ae75_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_17/bd_ae75_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_18/bd_ae75_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_19/bd_ae75_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_20/bd_ae75_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_21/bd_ae75_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_22/bd_ae75_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_23/bd_ae75_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_24/bd_ae75_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_25/bd_ae75_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_26/bd_ae75_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_processing_system7_0_0/rsa_soc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_processing_system7_0_0 || ORIG_REF_NAME==rsa_soc_processing_system7_0_0} -quiet] -quiet

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_ps7_0_axi_periph_0/rsa_soc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_ps7_0_axi_periph_0 || ORIG_REF_NAME==rsa_soc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_xbar_0/rsa_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_xbar_0 || ORIG_REF_NAME==rsa_soc_xbar_0} -quiet] -quiet

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rst_ps7_0_100M_0/rsa_soc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_rst_ps7_0_100M_0 || ORIG_REF_NAME==rsa_soc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rsa_soc_auto_pc_0 || ORIG_REF_NAME==rsa_soc_auto_pc_0} -quiet] -quiet

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rsa_dma_0/rsa_soc_rsa_dma_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_dma_0 || ORIG_REF_NAME==rsa_soc_rsa_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rsa_dma_0/rsa_soc_rsa_dma_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_dma_0 || ORIG_REF_NAME==rsa_soc_rsa_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rsa_dma_0/rsa_soc_rsa_dma_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rsa_acc_0/src/PYNQ-Z1_C.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_soc_rsa_acc_0 || ORIG_REF_NAME==rsa_soc_rsa_acc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_1/bd_ae75_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_1/bd_ae75_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_2/bd_ae75_arsw_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_3/bd_ae75_rsw_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_4/bd_ae75_awsw_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_5/bd_ae75_wsw_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_6/bd_ae75_bsw_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_10/bd_ae75_s00a2s_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_11/bd_ae75_sarn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_12/bd_ae75_srn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_16/bd_ae75_s01a2s_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_17/bd_ae75_sawn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_18/bd_ae75_swn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_19/bd_ae75_sbn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_20/bd_ae75_m00s2a_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_21/bd_ae75_m00arn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_22/bd_ae75_m00rn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_23/bd_ae75_m00awn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_24/bd_ae75_m00wn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/bd_0/ip/ip_25/bd_ae75_m00bn_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_axi_smc_0/ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_processing_system7_0_0/rsa_soc_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_soc_processing_system7_0_0 || ORIG_REF_NAME==rsa_soc_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_xbar_0/rsa_soc_xbar_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rst_ps7_0_100M_0/rsa_soc_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_soc_rst_ps7_0_100M_0 || ORIG_REF_NAME==rsa_soc_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rst_ps7_0_100M_0/rsa_soc_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rsa_soc_rst_ps7_0_100M_0 || ORIG_REF_NAME==rsa_soc_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_rst_ps7_0_100M_0/rsa_soc_rst_ps7_0_100M_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/ip/rsa_soc_auto_pc_0/rsa_soc_auto_pc_0_ooc.xdc

# XDC: /home/crfosse/dds1/TFE4141-DDS1/rsa_integration_kit/RSA_soc/boards/rsa_soc_ooc.xdc
