#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Sep 29 22:39:21 CEST 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 370952dc9ab94906a14a4cd41398f151 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mega_adder_tb_behav xil_defaultlib.mega_adder_tb -log elaborate.log"
xelab -wto 370952dc9ab94906a14a4cd41398f151 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mega_adder_tb_behav xil_defaultlib.mega_adder_tb -log elaborate.log

