#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Oct 27 19:26:18 CET 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 954f8105ad2d469494c91b4c37f31fbd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_blakley_behav xil_defaultlib.tb_blakley -log elaborate.log"
xelab -wto 954f8105ad2d469494c91b4c37f31fbd --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_blakley_behav xil_defaultlib.tb_blakley -log elaborate.log

